SELECT  T1.ICI, T2.UPI, T3.SSN, T3.FRST_NM , T3.MID_NM, T3.LST_NM, T3.MODFR FROM
.TWNPRGM_CASE_HSTRY T1,
.TWNCASE_MEMBER_HST T2,
.TWNPERSON T3 WHERE T1.PRGM_CASE_TYPE = 'FS' AND T1.PRGM_CASE_STS IN ('P', 'O') AND T1.RCRT_APL_DT BETWEEN AND T1.PRD_BEG_DT = 
AND T1.APPL_ACT_TYPE IN ('FA', 'RO', 'RC') AND T1.ICI = T2.ICI AND T2.UPI = T3.UPI AND T2.HH_LEFT_DT = '9999-12-31' AND T2.PRD_BEG_DT = 
AND T2.FS_ASST_IND = 'Y'AND NOT T2.FS_ELIG_CD IN ( '9', '3', ' ') AND NOT T2.ET_PRTCP_CD IN ( '07', '08') AND NOT T3.SSN LIKE '000%' AND NOT SSN LIKE '999%'AND T3.DOB <= CURRENT DATE - 18 YEARS AND NOT T2.UPI IN(SELECT S1.UPI FROM 
.TWNUERND_INCM_DTL S1 WHERE S1.UERND_INC_TYPE_CD = '45'AND (S1.PRD_END_DT = '9999-12-31'OR S1.PRD_END_DT = 
AND PRD_BEG_DT <= 
AND S1.UERND_INC_AMT > 0.0 AND NOT S1.UNE_INC_VERF_CD IN ('N', ' ', '?') AND  S1.MAINT_CD <> 'D')AND NOT T2.UPI IN ( SELECT J1.UPI FROM
.TWNJOB_INCM_DTLS J1,
.TWNPAY_DTLS J2 WHERE (J1.PRD_END_DT = '9999-12-31' OR J1.PRD_END_DT = 
AND J1.UPI = J2.UPI AND J1.INCM_SQ_NMB = J2.INCM_SQ_NMB AND J1.PRD_BEG_DT <= 		
AND J1.PRD_BEG_DT = J2.PRD_BEG_DT AND NOT J1.JOB_INC_VRFD_CD IN ('N', ' ') AND J1.MAINT_CD <> 'D' AND J2.PAID_DT = (SELECT MAX(P2.PAID_DT)FROM 
.TWNPAY_DTLS P2 WHERE P2.GRS_WGS_AMT > 0 AND P2.UPI = J2.UPI))ORDER BY T1.ICI , T2.UPI FOR FETCH ONLY WITH UR;	
